// ATLProject1.idl : ATLProject1 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ATLProject1.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(1C031CEF-7FB1-4BF0-AAFB-FAFE1BCCEB18),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

